import type { Case } from "@/types/case";

export const mockCases: Case[] = [
  {
    id: "case-001",
    caseNumber: "LC-2026-001",
    title: "Harrington Enterprises — Corporate Contract Dispute",
    description: "Dispute arising from breach of a $4.2M supply agreement between Harrington Enterprises and Pacific Distribution Inc. The matter involves allegations of non-performance, delayed deliveries, and consequential damages affecting downstream operations.",
    clientId: "cli-001",
    clientName: "Harrington Enterprises Ltd.",
    lawyerId: "law-001",
    lawyerName: "Eleanor Voss",
    caseType: "corporate",
    status: "active",
    priority: "high",
    courtName: "New York Supreme Court, Commercial Division",
    filingDate: "2026-03-15",
    nextHearingDate: "2026-09-22",
    timeline: [
      { id: "tl-001", date: "2026-03-15", title: "Case Filed", description: "Initial complaint filed with the Commercial Division.", type: "filing" },
      { id: "tl-002", date: "2026-04-10", title: "Discovery Commenced", description: "Document production requests served on opposing counsel.", type: "document" },
      { id: "tl-003", date: "2026-06-20", title: "Preliminary Hearing", description: "Judge reviewed discovery schedule and set trial timeline.", type: "hearing" },
    ],
    notes: [
      { id: "n-001", content: "Client prefers mediation before trial. Explore settlement options.", createdBy: "Eleanor Voss", createdAt: "2026-04-15T10:00:00Z" },
    ],
    documentIds: ["doc-001", "doc-002", "doc-003"],
    totalBilled: 85000,
    totalPaid: 65000,
    createdAt: "2026-03-10T08:00:00Z",
    updatedAt: "2026-09-08T10:30:00Z",
  },
  {
    id: "case-002",
    caseNumber: "LC-2026-002",
    title: "Whitfield v. Anderson — Employment Discrimination Claim",
    description: "James Whitfield alleges wrongful termination and age discrimination by his former employer, Anderson & Associates. The matter involves claims under Title VII and the Age Discrimination in Employment Act, with potential compensatory and punitive damages.",
    clientId: "cli-002",
    clientName: "James Whitfield",
    lawyerId: "law-002",
    lawyerName: "Marcus Hale",
    caseType: "employment",
    status: "active",
    priority: "high",
    courtName: "U.S. District Court, Southern District of New York",
    filingDate: "2026-02-10",
    nextHearingDate: "2026-09-18",
    timeline: [
      { id: "tl-004", date: "2026-02-10", title: "Complaint Filed", description: "Federal complaint filed alleging employment discrimination.", type: "filing" },
      { id: "tl-005", date: "2026-04-05", title: "Motion to Dismiss Denied", description: "Court denied defendant's motion to dismiss on all counts.", type: "hearing" },
    ],
    notes: [],
    documentIds: ["doc-004", "doc-005"],
    totalBilled: 62000,
    totalPaid: 50000,
    createdAt: "2026-02-05T09:00:00Z",
    updatedAt: "2026-09-06T14:00:00Z",
  },
  {
    id: "case-003",
    caseNumber: "LC-2026-003",
    title: "Meridian Healthcare — Regulatory Investigation Defense",
    description: "Defense of Meridian Healthcare Group against a regulatory investigation by the Office of Inspector General regarding Medicare billing practices. The investigation involves review of billing records spanning three fiscal years.",
    clientId: "cli-003",
    clientName: "Meridian Healthcare Group",
    lawyerId: "law-003",
    lawyerName: "Amara Sterling",
    caseType: "criminal",
    status: "under-review",
    priority: "urgent",
    courtName: "Administrative Proceeding — OIG",
    filingDate: "2026-04-20",
    nextHearingDate: "2026-09-25",
    timeline: [
      { id: "tl-006", date: "2026-04-20", title: "Investigation Notified", description: "Client received formal notice of OIG investigation.", type: "filing" },
      { id: "tl-007", date: "2026-06-15", title: "Document Production", description: "First tranche of billing records produced to investigators.", type: "document" },
    ],
    notes: [
      { id: "n-002", content: "Coordination with external forensic accountants required for billing analysis.", createdBy: "Amara Sterling", createdAt: "2026-05-10T14:00:00Z" },
    ],
    documentIds: ["doc-006", "doc-007"],
    totalBilled: 125000,
    totalPaid: 100000,
    createdAt: "2026-04-18T10:00:00Z",
    updatedAt: "2026-09-05T09:30:00Z",
  },
  {
    id: "case-004",
    caseNumber: "LC-2026-004",
    title: "Ashworth Estate — Succession and Trust Dispute",
    description: "Complex estate dispute involving the Ashworth Family Trust, with competing claims from three beneficiaries regarding the distribution of assets valued at approximately $28 million, including real property across multiple jurisdictions.",
    clientId: "cli-004",
    clientName: "Victoria Ashworth",
    lawyerId: "law-004",
    lawyerName: "Julian Mercer",
    caseType: "family",
    status: "active",
    priority: "high",
    courtName: "Surrogate's Court, New York County",
    filingDate: "2026-01-18",
    nextHearingDate: "2026-10-05",
    timeline: [
      { id: "tl-008", date: "2026-01-18", title: "Petition Filed", description: "Petition filed to contest trust distribution terms.", type: "filing" },
      { id: "tl-009", date: "2026-03-22", title: "Mediation Session", description: "First mediation session with all beneficiaries. Partial progress.", type: "hearing" },
      { id: "tl-010", date: "2026-07-10", title: "Property Appraisals", description: "Independent appraisals completed for all trust properties.", type: "document" },
    ],
    notes: [],
    documentIds: ["doc-008", "doc-009"],
    totalBilled: 95000,
    totalPaid: 80000,
    createdAt: "2026-01-15T11:00:00Z",
    updatedAt: "2026-09-03T15:00:00Z",
  },
  {
    id: "case-005",
    caseNumber: "LC-2026-005",
    title: "Harrington Enterprises — Merger Compliance Review",
    description: "Advisory engagement for regulatory compliance review in connection with Harrington Enterprises' proposed acquisition of Pacific Coast Manufacturing. Includes antitrust analysis, due diligence coordination, and regulatory filing preparation.",
    clientId: "cli-001",
    clientName: "Harrington Enterprises Ltd.",
    lawyerId: "law-001",
    lawyerName: "Eleanor Voss",
    caseType: "corporate",
    status: "pending",
    priority: "medium",
    filingDate: "2026-05-20",
    timeline: [
      { id: "tl-011", date: "2026-05-20", title: "Engagement Commenced", description: "Client engagement letter signed for merger advisory.", type: "filing" },
      { id: "tl-012", date: "2026-07-01", title: "Due Diligence Report", description: "Preliminary due diligence findings presented to the board.", type: "document" },
    ],
    notes: [],
    documentIds: ["doc-010"],
    totalBilled: 48000,
    totalPaid: 48000,
    createdAt: "2026-05-18T09:00:00Z",
    updatedAt: "2026-09-01T10:00:00Z",
  },
  {
    id: "case-006",
    caseNumber: "LC-2026-006",
    title: "Northstar Technologies — Patent Infringement Claim",
    description: "Northstar Technologies asserts infringement of three software method patents by competitor DataFlow Systems. The dispute involves claims related to machine learning algorithms and data processing pipelines critical to Northstar's core product offering.",
    clientId: "cli-005",
    clientName: "Northstar Technologies Inc.",
    lawyerId: "law-005",
    lawyerName: "Sophia Castillo",
    caseType: "intellectual-property",
    status: "active",
    priority: "high",
    courtName: "U.S. District Court, Northern District of California",
    filingDate: "2026-04-05",
    nextHearingDate: "2026-09-30",
    timeline: [
      { id: "tl-013", date: "2026-04-05", title: "Patent Complaint Filed", description: "Complaint asserting infringement of US Patents 10,234,567; 10,345,678; and 10,456,789.", type: "filing" },
    ],
    notes: [],
    documentIds: ["doc-011", "doc-012"],
    totalBilled: 110000,
    totalPaid: 75000,
    createdAt: "2026-04-01T08:00:00Z",
    updatedAt: "2026-09-02T16:30:00Z",
  },
  {
    id: "case-007",
    caseNumber: "LC-2026-007",
    title: "Mitchell — Executive Separation Negotiation",
    description: "Confidential negotiation of an executive separation agreement for Sarah Mitchell following her departure from a Fortune 100 financial services company. Involves non-compete restrictions, deferred compensation, and equity vesting provisions.",
    clientId: "cli-008",
    clientName: "Sarah Mitchell",
    lawyerId: "law-002",
    lawyerName: "Marcus Hale",
    caseType: "employment",
    status: "active",
    priority: "medium",
    filingDate: "2026-06-10",
    timeline: [
      { id: "tl-014", date: "2026-06-10", title: "Engagement Commenced", description: "Client retained for executive separation advisory.", type: "filing" },
      { id: "tl-015", date: "2026-07-20", title: "Initial Proposal Delivered", description: "Separation proposal sent to employer's counsel.", type: "document" },
    ],
    notes: [],
    documentIds: ["doc-013"],
    totalBilled: 35000,
    totalPaid: 25000,
    createdAt: "2026-06-08T10:00:00Z",
    updatedAt: "2026-09-04T14:00:00Z",
  },
  {
    id: "case-008",
    caseNumber: "LC-2026-008",
    title: "Chen Family — Property Ownership Dispute",
    description: "Dispute concerning ownership rights to a commercial property at 550 Broadway, with competing claims between the Chen family trust and a former business partner. Involves interpretation of a partnership agreement and equitable remedies.",
    clientId: "cli-006",
    clientName: "Robert & Margaret Chen",
    lawyerId: "law-004",
    lawyerName: "Julian Mercer",
    caseType: "real-estate",
    status: "active",
    priority: "medium",
    courtName: "New York Supreme Court",
    filingDate: "2026-03-28",
    nextHearingDate: "2026-10-12",
    timeline: [
      { id: "tl-016", date: "2026-03-28", title: "Action Commenced", description: "Complaint filed asserting ownership rights and seeking declaratory judgment.", type: "filing" },
    ],
    notes: [],
    documentIds: ["doc-014"],
    totalBilled: 55000,
    totalPaid: 40000,
    createdAt: "2026-03-25T09:30:00Z",
    updatedAt: "2026-08-30T11:00:00Z",
  },
  {
    id: "case-009",
    caseNumber: "LC-2026-009",
    title: "Meridian Healthcare — HIPAA Compliance Remediation",
    description: "Advisory engagement to develop and implement a comprehensive HIPAA compliance program following identification of potential data security vulnerabilities in patient record management systems.",
    clientId: "cli-003",
    clientName: "Meridian Healthcare Group",
    lawyerId: "law-003",
    lawyerName: "Amara Sterling",
    caseType: "legal-consultancy",
    status: "pending",
    priority: "medium",
    filingDate: "2026-07-15",
    timeline: [
      { id: "tl-017", date: "2026-07-15", title: "Assessment Initiated", description: "Preliminary compliance assessment commenced.", type: "filing" },
    ],
    notes: [],
    documentIds: [],
    totalBilled: 28000,
    totalPaid: 20000,
    createdAt: "2026-07-12T10:00:00Z",
    updatedAt: "2026-09-05T09:00:00Z",
  },
  {
    id: "case-010",
    caseNumber: "LC-2026-010",
    title: "Northstar Technologies — Trade Secret Misappropriation",
    description: "Northstar alleges that a former senior engineer misappropriated proprietary source code and trade secrets upon departing to join a competing startup. Emergency injunctive relief was obtained to prevent further use or disclosure.",
    clientId: "cli-005",
    clientName: "Northstar Technologies Inc.",
    lawyerId: "law-005",
    lawyerName: "Sophia Castillo",
    caseType: "intellectual-property",
    status: "active",
    priority: "urgent",
    courtName: "Superior Court of California, Santa Clara County",
    filingDate: "2026-08-01",
    nextHearingDate: "2026-09-15",
    timeline: [
      { id: "tl-018", date: "2026-08-01", title: "Emergency TRO Obtained", description: "Temporary restraining order granted by the court.", type: "hearing" },
      { id: "tl-019", date: "2026-08-15", title: "Preliminary Injunction Hearing", description: "Court granted preliminary injunction pending trial.", type: "hearing" },
    ],
    notes: [],
    documentIds: ["doc-015", "doc-016"],
    totalBilled: 72000,
    totalPaid: 50000,
    createdAt: "2026-07-28T08:00:00Z",
    updatedAt: "2026-09-08T15:00:00Z",
  },
  {
    id: "case-011",
    caseNumber: "LC-2026-011",
    title: "Pinnacle Financial — Tax Structure Optimization",
    description: "Strategic tax advisory for Pinnacle Financial Services to restructure its holding company arrangement across three jurisdictions, optimizing for tax efficiency while maintaining full regulatory compliance.",
    clientId: "cli-007",
    clientName: "Pinnacle Financial Services",
    lawyerId: "law-006",
    lawyerName: "Richard Thorpe",
    caseType: "tax-compliance",
    status: "active",
    priority: "medium",
    filingDate: "2026-05-01",
    timeline: [
      { id: "tl-020", date: "2026-05-01", title: "Engagement Commenced", description: "Tax optimization advisory engagement signed.", type: "filing" },
    ],
    notes: [],
    documentIds: ["doc-017"],
    totalBilled: 92000,
    totalPaid: 75000,
    createdAt: "2026-04-28T10:00:00Z",
    updatedAt: "2026-09-06T11:30:00Z",
  },
  {
    id: "case-012",
    caseNumber: "LC-2026-012",
    title: "Metropolitan Publishing — Copyright Licensing Dispute",
    description: "Dispute between Metropolitan Publishing House and three authors over digital licensing rights for a backlist catalog of 140 titles. The controversy centers on interpretation of pre-digital-era publishing agreements.",
    clientId: "cli-015",
    clientName: "Metropolitan Publishing House",
    lawyerId: "law-001",
    lawyerName: "Eleanor Voss",
    caseType: "intellectual-property",
    status: "pending",
    priority: "medium",
    courtName: "U.S. District Court, Southern District of New York",
    filingDate: "2026-06-25",
    nextHearingDate: "2026-10-20",
    timeline: [],
    notes: [],
    documentIds: ["doc-018"],
    totalBilled: 42000,
    totalPaid: 30000,
    createdAt: "2026-06-22T09:00:00Z",
    updatedAt: "2026-09-05T14:00:00Z",
  },
  {
    id: "case-013",
    caseNumber: "LC-2026-013",
    title: "Pinnacle Financial — SEC Reporting Compliance",
    description: "Advisory on SEC reporting obligations following Pinnacle's recent acquisition, including registration statement amendments, beneficial ownership filings, and ongoing periodic reporting requirements.",
    clientId: "cli-007",
    clientName: "Pinnacle Financial Services",
    lawyerId: "law-006",
    lawyerName: "Richard Thorpe",
    caseType: "tax-compliance",
    status: "active",
    priority: "high",
    filingDate: "2026-07-10",
    timeline: [],
    notes: [],
    documentIds: [],
    totalBilled: 38000,
    totalPaid: 30000,
    createdAt: "2026-07-08T10:00:00Z",
    updatedAt: "2026-09-07T09:00:00Z",
  },
  {
    id: "case-014",
    caseNumber: "LC-2026-014",
    title: "Dominion Real Estate — Commercial Lease Dispute",
    description: "Dispute with a commercial tenant over lease termination provisions and holdover damages at a Class A office building in Midtown Manhattan. Claimed damages exceed $1.2 million in lost rent and property modifications.",
    clientId: "cli-009",
    clientName: "Dominion Real Estate Partners",
    lawyerId: "law-007",
    lawyerName: "Diana Prescott",
    caseType: "real-estate",
    status: "active",
    priority: "medium",
    courtName: "New York Supreme Court",
    filingDate: "2026-05-15",
    nextHearingDate: "2026-09-28",
    timeline: [],
    notes: [],
    documentIds: ["doc-019"],
    totalBilled: 45000,
    totalPaid: 35000,
    createdAt: "2026-05-12T11:00:00Z",
    updatedAt: "2026-09-01T16:00:00Z",
  },
  {
    id: "case-015",
    caseNumber: "LC-2025-015",
    title: "Ashworth Estate — Tax Planning Advisory",
    description: "Comprehensive estate tax planning for the Ashworth family, involving irrevocable trust restructuring, charitable giving strategies, and generation-skipping transfer tax mitigation across a multi-state asset portfolio.",
    clientId: "cli-004",
    clientName: "Victoria Ashworth",
    lawyerId: "law-004",
    lawyerName: "Julian Mercer",
    caseType: "tax-compliance",
    status: "closed",
    priority: "low",
    filingDate: "2025-08-10",
    closingDate: "2026-04-15",
    timeline: [],
    notes: [],
    documentIds: [],
    totalBilled: 68000,
    totalPaid: 68000,
    createdAt: "2025-08-08T09:00:00Z",
    updatedAt: "2026-04-15T16:00:00Z",
  },
  {
    id: "case-016",
    caseNumber: "LC-2026-016",
    title: "Dominion Real Estate — Zoning Variance Application",
    description: "Representation of Dominion in a contested zoning variance application for a mixed-use development project in Lower Manhattan, involving community board hearings and environmental impact considerations.",
    clientId: "cli-009",
    clientName: "Dominion Real Estate Partners",
    lawyerId: "law-007",
    lawyerName: "Diana Prescott",
    caseType: "real-estate",
    status: "pending",
    priority: "medium",
    filingDate: "2026-08-05",
    timeline: [],
    notes: [],
    documentIds: [],
    totalBilled: 18000,
    totalPaid: 15000,
    createdAt: "2026-08-03T10:00:00Z",
    updatedAt: "2026-09-04T13:00:00Z",
  },
  {
    id: "case-017",
    caseNumber: "LC-2026-017",
    title: "Kessler v. Apex Capital — Non-Compete Enforcement",
    description: "Thomas Kessler seeks to enforce a non-compete agreement against Apex Capital, his former employer, which is allegedly recruiting his team and soliciting his clients in violation of restrictive covenant agreements.",
    clientId: "cli-010",
    clientName: "Thomas Kessler",
    lawyerId: "law-008",
    lawyerName: "Nathan Cross",
    caseType: "employment",
    status: "active",
    priority: "high",
    courtName: "New York Supreme Court, Commercial Division",
    filingDate: "2026-07-22",
    nextHearingDate: "2026-09-20",
    timeline: [],
    notes: [],
    documentIds: ["doc-020"],
    totalBilled: 28000,
    totalPaid: 20000,
    createdAt: "2026-07-20T09:00:00Z",
    updatedAt: "2026-09-07T10:30:00Z",
  },
  {
    id: "case-018",
    caseNumber: "LC-2026-018",
    title: "Atlas Infrastructure — Government Contract Review",
    description: "Review and negotiation of a $45 million federal infrastructure contract, including compliance with Federal Acquisition Regulation, prevailing wage requirements, and minority business enterprise participation goals.",
    clientId: "cli-011",
    clientName: "Atlas Infrastructure Corp.",
    lawyerId: "law-009",
    lawyerName: "Catherine Blackwell",
    caseType: "contract",
    status: "active",
    priority: "medium",
    filingDate: "2026-06-01",
    timeline: [],
    notes: [],
    documentIds: ["doc-021"],
    totalBilled: 52000,
    totalPaid: 45000,
    createdAt: "2026-05-28T10:00:00Z",
    updatedAt: "2026-08-25T15:00:00Z",
  },
  {
    id: "case-019",
    caseNumber: "LC-2026-019",
    title: "Atlas Infrastructure — Construction Defect Claim",
    description: "Defense of Atlas Infrastructure against a construction defect claim arising from a commercial building project, involving allegations of structural engineering deficiencies and waterproofing failures.",
    clientId: "cli-011",
    clientName: "Atlas Infrastructure Corp.",
    lawyerId: "law-009",
    lawyerName: "Catherine Blackwell",
    caseType: "civil-litigation",
    status: "on-hold",
    priority: "low",
    courtName: "New York Supreme Court",
    filingDate: "2026-08-15",
    timeline: [],
    notes: [],
    documentIds: [],
    totalBilled: 15000,
    totalPaid: 10000,
    createdAt: "2026-08-12T09:00:00Z",
    updatedAt: "2026-09-01T11:00:00Z",
  },
  {
    id: "case-020",
    caseNumber: "LC-2026-020",
    title: "Drake — International Tax Advisory",
    description: "Cross-border tax planning and compliance advisory for William Drake III, a dual UK-US citizen with investment portfolios, real estate holdings, and business interests in both jurisdictions.",
    clientId: "cli-014",
    clientName: "William Drake III",
    lawyerId: "law-010",
    lawyerName: "Alexander Grant",
    caseType: "tax-compliance",
    status: "active",
    priority: "medium",
    filingDate: "2026-08-20",
    timeline: [],
    notes: [],
    documentIds: [],
    totalBilled: 22000,
    totalPaid: 15000,
    createdAt: "2026-08-18T10:00:00Z",
    updatedAt: "2026-09-07T09:30:00Z",
  },
];
