import type { Client } from "@/types/client";

export const mockClients: Client[] = [
  {
    id: "cli-001",
    name: "Harrington Enterprises Ltd.",
    email: "legal@harrington-ent.com",
    phone: "+1 212-555-0201",
    address: "450 Park Avenue, Suite 2200",
    city: "New York",
    state: "NY",
    zipCode: "10022",
    clientType: "corporate",
    status: "active",
    company: "Harrington Enterprises Ltd.",
    designation: "Board of Directors",
    caseIds: ["case-001", "case-005"],
    totalCases: 4,
    notes: "Long-standing client since 2018. Preferred contact through legal department.",
    createdAt: "2024-02-15T10:00:00Z",
    updatedAt: "2026-09-01T08:30:00Z",
  },
  {
    id: "cli-002",
    name: "James Whitfield",
    email: "j.whitfield@email.com",
    phone: "+1 212-555-0202",
    address: "88 Greenwich Street, Apt 14C",
    city: "New York",
    state: "NY",
    zipCode: "10006",
    clientType: "individual",
    status: "active",
    designation: "CEO, Whitfield Capital",
    caseIds: ["case-002"],
    totalCases: 2,
    notes: "High-net-worth individual. Requires discretion on all matters.",
    createdAt: "2024-03-20T14:00:00Z",
    updatedAt: "2026-08-28T12:00:00Z",
  },
  {
    id: "cli-003",
    name: "Meridian Healthcare Group",
    email: "counsel@meridianhg.com",
    phone: "+1 212-555-0203",
    address: "1 World Trade Center, Floor 72",
    city: "New York",
    state: "NY",
    zipCode: "10007",
    clientType: "corporate",
    status: "active",
    company: "Meridian Healthcare Group",
    designation: "General Counsel Office",
    caseIds: ["case-003", "case-009"],
    totalCases: 5,
    notes: "Healthcare sector. HIPAA compliance considerations apply to all documents.",
    createdAt: "2024-04-10T09:30:00Z",
    updatedAt: "2026-09-05T16:45:00Z",
  },
  {
    id: "cli-004",
    name: "Victoria Ashworth",
    email: "v.ashworth@ashworthfamily.com",
    phone: "+1 212-555-0204",
    address: "740 Park Avenue, Penthouse B",
    city: "New York",
    state: "NY",
    zipCode: "10021",
    clientType: "individual",
    status: "active",
    designation: "Heiress, Ashworth Family Trust",
    caseIds: ["case-004"],
    totalCases: 3,
    notes: "Estate and family matters. Highly sensitive. Only senior partners.",
    createdAt: "2024-05-01T11:00:00Z",
    updatedAt: "2026-09-03T10:15:00Z",
  },
  {
    id: "cli-005",
    name: "Northstar Technologies Inc.",
    email: "legal@northstartech.io",
    phone: "+1 415-555-0205",
    address: "525 Market Street, Suite 3100",
    city: "San Francisco",
    state: "CA",
    zipCode: "94105",
    clientType: "corporate",
    status: "active",
    company: "Northstar Technologies Inc.",
    designation: "VP Legal Affairs",
    caseIds: ["case-006", "case-010"],
    totalCases: 3,
    notes: "Technology company. IP matters and corporate advisory. Fast-paced engagement.",
    createdAt: "2024-06-15T08:00:00Z",
    updatedAt: "2026-09-02T14:30:00Z",
  },
  {
    id: "cli-006",
    name: "Robert & Margaret Chen",
    email: "rchen@chenholdings.com",
    phone: "+1 212-555-0206",
    address: "200 Central Park South, Unit 3201",
    city: "New York",
    state: "NY",
    zipCode: "10019",
    clientType: "individual",
    status: "active",
    designation: "Founders, Chen Holdings",
    caseIds: ["case-008"],
    totalCases: 2,
    notes: "Real estate and family estate planning. Multi-generational wealth management.",
    createdAt: "2024-07-20T13:00:00Z",
    updatedAt: "2026-08-30T09:00:00Z",
  },
  {
    id: "cli-007",
    name: "Pinnacle Financial Services",
    email: "compliance@pinnaclefs.com",
    phone: "+1 212-555-0207",
    address: "383 Madison Avenue, Floor 40",
    city: "New York",
    state: "NY",
    zipCode: "10179",
    clientType: "corporate",
    status: "active",
    company: "Pinnacle Financial Services",
    designation: "Chief Compliance Officer",
    caseIds: ["case-011", "case-013"],
    totalCases: 4,
    notes: "Financial services. Regulatory compliance and tax matters. SEC filing considerations.",
    createdAt: "2024-08-05T10:30:00Z",
    updatedAt: "2026-09-06T11:00:00Z",
  },
  {
    id: "cli-008",
    name: "Sarah Mitchell",
    email: "s.mitchell@mitchellgroup.com",
    phone: "+1 212-555-0208",
    address: "15 Central Park West, Unit 24D",
    city: "New York",
    state: "NY",
    zipCode: "10023",
    clientType: "individual",
    status: "active",
    designation: "Managing Director, Mitchell Group",
    caseIds: ["case-007"],
    totalCases: 1,
    notes: "Employment dispute. Confidential separation negotiations.",
    createdAt: "2024-09-10T15:00:00Z",
    updatedAt: "2026-09-04T08:45:00Z",
  },
  {
    id: "cli-009",
    name: "Dominion Real Estate Partners",
    email: "legal@dominionrep.com",
    phone: "+1 212-555-0209",
    address: "60 Hudson Street, Floor 15",
    city: "New York",
    state: "NY",
    zipCode: "10013",
    clientType: "corporate",
    status: "active",
    company: "Dominion Real Estate Partners",
    designation: "Managing Partner",
    caseIds: ["case-014", "case-016"],
    totalCases: 3,
    notes: "Commercial real estate development. Active portfolio across tri-state area.",
    createdAt: "2024-10-01T09:00:00Z",
    updatedAt: "2026-09-01T16:30:00Z",
  },
  {
    id: "cli-010",
    name: "Thomas Kessler",
    email: "tkessler@kesslerventures.com",
    phone: "+1 212-555-0210",
    address: "432 West 58th Street, Apt 8A",
    city: "New York",
    state: "NY",
    zipCode: "10019",
    clientType: "individual",
    status: "active",
    designation: "Founder, Kessler Ventures",
    caseIds: ["case-017"],
    totalCases: 1,
    notes: "Employment matter. Non-compete and trade secrets dispute.",
    createdAt: "2024-11-15T11:30:00Z",
    updatedAt: "2026-09-07T10:00:00Z",
  },
  {
    id: "cli-011",
    name: "Atlas Infrastructure Corp.",
    email: "legal@atlasinfra.com",
    phone: "+1 212-555-0211",
    address: "277 Park Avenue, Suite 4500",
    city: "New York",
    state: "NY",
    zipCode: "10172",
    clientType: "corporate",
    status: "active",
    company: "Atlas Infrastructure Corp.",
    designation: "Head of Legal",
    caseIds: ["case-018", "case-019"],
    totalCases: 2,
    notes: "Infrastructure and construction sector. Government contract compliance.",
    createdAt: "2025-01-08T10:00:00Z",
    updatedAt: "2026-08-25T14:15:00Z",
  },
  {
    id: "cli-012",
    name: "Elena Rodriguez",
    email: "e.rodriguez@email.com",
    phone: "+1 212-555-0212",
    address: "320 East 72nd Street, Apt 5B",
    city: "New York",
    state: "NY",
    zipCode: "10021",
    clientType: "individual",
    status: "inactive",
    designation: "Entrepreneur",
    caseIds: [],
    totalCases: 1,
    notes: "Previous family law matter. Case concluded. May return for estate planning.",
    createdAt: "2025-02-20T14:00:00Z",
    updatedAt: "2026-06-15T09:30:00Z",
  },
  {
    id: "cli-013",
    name: "Cascade Ventures LLC",
    email: "ops@cascadeventures.com",
    phone: "+1 212-555-0213",
    address: "100 Wall Street, Suite 800",
    city: "New York",
    state: "NY",
    zipCode: "10005",
    clientType: "corporate",
    status: "prospect",
    company: "Cascade Ventures LLC",
    designation: "COO",
    caseIds: [],
    totalCases: 0,
    notes: "Prospective client. Initial consultation completed. Awaiting engagement decision.",
    createdAt: "2026-08-01T10:00:00Z",
    updatedAt: "2026-09-08T11:00:00Z",
  },
  {
    id: "cli-014",
    name: "William Drake III",
    email: "w.drake@drakeoffice.com",
    phone: "+1 212-555-0214",
    address: "1040 Fifth Avenue, Apt 12A",
    city: "New York",
    state: "NY",
    zipCode: "10028",
    clientType: "individual",
    status: "active",
    designation: "Private Investor",
    caseIds: ["case-020"],
    totalCases: 2,
    notes: "Private wealth. Multi-jurisdictional tax planning. London and New York residences.",
    createdAt: "2025-05-12T09:00:00Z",
    updatedAt: "2026-09-07T08:00:00Z",
  },
  {
    id: "cli-015",
    name: "Metropolitan Publishing House",
    email: "legal@metropublishing.com",
    phone: "+1 212-555-0215",
    address: "1745 Broadway, Floor 18",
    city: "New York",
    state: "NY",
    zipCode: "10019",
    clientType: "corporate",
    status: "active",
    company: "Metropolitan Publishing House",
    designation: "VP Legal & Business Affairs",
    caseIds: ["case-012"],
    totalCases: 2,
    notes: "Media and publishing. IP licensing and contract disputes. Copyright expertise required.",
    createdAt: "2025-06-20T11:00:00Z",
    updatedAt: "2026-09-05T13:45:00Z",
  },
];
