import type { Hearing } from "@/types/hearing";

export const mockHearings: Hearing[] = [
  { id: "hr-001", title: "Harrington v. Pacific Distribution — Status Conference", caseId: "case-001", caseName: "Harrington Enterprises — Corporate Contract Dispute", clientId: "cli-001", clientName: "Harrington Enterprises Ltd.", lawyerId: "law-001", lawyerName: "Eleanor Voss", courtName: "New York Supreme Court, Commercial Division", courtRoom: "Courtroom 12A", judge: "Hon. Katherine Marlowe", date: "2026-09-22", time: "09:30", duration: "1 hour", status: "scheduled", notes: "Status conference to discuss discovery deadlines and trial schedule.", createdAt: "2026-08-15T10:00:00Z", updatedAt: "2026-09-08T09:00:00Z" },
  { id: "hr-002", title: "Whitfield v. Anderson — Deposition Hearing", caseId: "case-002", caseName: "Whitfield v. Anderson — Employment Discrimination Claim", clientId: "cli-002", clientName: "James Whitfield", lawyerId: "law-002", lawyerName: "Marcus Hale", courtName: "U.S. District Court, SDNY", courtRoom: "Conference Room 8B", judge: "Hon. Robert Chen", date: "2026-09-18", time: "10:00", duration: "3 hours", status: "scheduled", notes: "Deposition of former supervisor and HR director.", createdAt: "2026-08-20T14:00:00Z", updatedAt: "2026-09-06T11:00:00Z" },
  { id: "hr-003", title: "Meridian Healthcare — OIG Interview Session", caseId: "case-003", caseName: "Meridian Healthcare — Regulatory Investigation Defense", clientId: "cli-003", clientName: "Meridian Healthcare Group", lawyerId: "law-003", lawyerName: "Amara Sterling", courtName: "Office of Inspector General", courtRoom: "Interview Room 3", date: "2026-09-25", time: "14:00", duration: "2 hours", status: "scheduled", notes: "Scheduled interview of CFO by OIG investigators. Client to be prepared.", createdAt: "2026-08-25T09:00:00Z", updatedAt: "2026-09-05T10:00:00Z" },
  { id: "hr-004", title: "Northstar v. DataFlow — Markman Hearing", caseId: "case-006", caseName: "Northstar Technologies — Patent Infringement Claim", clientId: "cli-005", clientName: "Northstar Technologies Inc.", lawyerId: "law-005", lawyerName: "Sophia Castillo", courtName: "U.S. District Court, ND California", courtRoom: "Courtroom 5", judge: "Hon. Michelle Torres", date: "2026-09-30", time: "09:00", duration: "Full day", status: "scheduled", notes: "Claim construction hearing. Critical to patent scope determination.", createdAt: "2026-07-15T10:00:00Z", updatedAt: "2026-09-02T15:00:00Z" },
  { id: "hr-005", title: "Ashworth Estate — Second Mediation Session", caseId: "case-004", caseName: "Ashworth Estate — Succession and Trust Dispute", clientId: "cli-004", clientName: "Victoria Ashworth", lawyerId: "law-004", lawyerName: "Julian Mercer", courtName: "Surrogate's Court, New York County", courtRoom: "Mediation Suite", judge: "Mediator: James Crawford", date: "2026-10-05", time: "10:00", duration: "4 hours", status: "scheduled", notes: "Second mediation attempt. All three beneficiaries and counsel to attend.", createdAt: "2026-09-01T11:00:00Z", updatedAt: "2026-09-03T14:00:00Z" },
  { id: "hr-006", title: "Northstar — TRO Extension Hearing", caseId: "case-010", caseName: "Northstar Technologies — Trade Secret Misappropriation", clientId: "cli-005", clientName: "Northstar Technologies Inc.", lawyerId: "law-005", lawyerName: "Sophia Castillo", courtName: "Superior Court of California, Santa Clara", courtRoom: "Courtroom 8", judge: "Hon. David Kim", date: "2026-09-15", time: "11:00", duration: "2 hours", status: "scheduled", notes: "Hearing on motion to extend temporary restraining order.", createdAt: "2026-08-20T08:00:00Z", updatedAt: "2026-09-08T10:00:00Z" },
  { id: "hr-007", title: "Kessler v. Apex Capital — Preliminary Conference", caseId: "case-017", caseName: "Kessler v. Apex Capital — Non-Compete Enforcement", clientId: "cli-010", clientName: "Thomas Kessler", lawyerId: "law-008", lawyerName: "Nathan Cross", courtName: "New York Supreme Court, Commercial Division", courtRoom: "Courtroom 6B", judge: "Hon. Sandra Wells", date: "2026-09-20", time: "14:30", duration: "45 minutes", status: "scheduled", notes: "Initial preliminary conference to set case schedule.", createdAt: "2026-08-10T10:00:00Z", updatedAt: "2026-09-07T09:00:00Z" },
  { id: "hr-008", title: "Dominion Real Estate — Lease Dispute Motion", caseId: "case-014", caseName: "Dominion Real Estate — Commercial Lease Dispute", clientId: "cli-009", clientName: "Dominion Real Estate Partners", lawyerId: "law-007", lawyerName: "Diana Prescott", courtName: "New York Supreme Court", courtRoom: "Courtroom 9", judge: "Hon. Michael Grant", date: "2026-09-28", time: "10:30", duration: "1.5 hours", status: "scheduled", notes: "Motion for partial summary judgment on holdover damages.", createdAt: "2026-08-28T11:00:00Z", updatedAt: "2026-09-04T14:00:00Z" },
  { id: "hr-009", title: "Metropolitan Publishing — Settlement Conference", caseId: "case-012", caseName: "Metropolitan Publishing — Copyright Licensing Dispute", clientId: "cli-015", clientName: "Metropolitan Publishing House", lawyerId: "law-001", lawyerName: "Eleanor Voss", courtName: "U.S. District Court, SDNY", courtRoom: "Settlement Conference Room", judge: "Magistrate Judge Lisa Park", date: "2026-10-20", time: "09:30", duration: "Half day", status: "scheduled", notes: "Court-ordered settlement conference with all three author-plaintiffs.", createdAt: "2026-09-05T10:00:00Z", updatedAt: "2026-09-05T10:00:00Z" },
  { id: "hr-010", title: "Chen Family — Pre-Trial Conference", caseId: "case-008", caseName: "Chen Family — Property Ownership Dispute", clientId: "cli-006", clientName: "Robert & Margaret Chen", lawyerId: "law-004", lawyerName: "Julian Mercer", courtName: "New York Supreme Court", courtRoom: "Courtroom 3", judge: "Hon. Anthony Russo", date: "2026-10-12", time: "11:00", duration: "1 hour", status: "scheduled", notes: "Pre-trial conference. Expected to discuss potential settlement framework.", createdAt: "2026-09-02T09:00:00Z", updatedAt: "2026-09-02T09:00:00Z" },
  { id: "hr-011", title: "Harrington v. Pacific — Discovery Motion Hearing", caseId: "case-001", caseName: "Harrington Enterprises — Corporate Contract Dispute", clientId: "cli-001", clientName: "Harrington Enterprises Ltd.", lawyerId: "law-001", lawyerName: "Eleanor Voss", courtName: "New York Supreme Court, Commercial Division", courtRoom: "Courtroom 12A", judge: "Hon. Katherine Marlowe", date: "2026-06-20", time: "09:30", duration: "1 hour", status: "completed", outcome: "Discovery schedule established. Document production deadline set for August 15.", createdAt: "2026-05-15T10:00:00Z", updatedAt: "2026-06-20T16:00:00Z" },
  { id: "hr-012", title: "Whitfield v. Anderson — Motion to Dismiss", caseId: "case-002", caseName: "Whitfield v. Anderson — Employment Discrimination Claim", clientId: "cli-002", clientName: "James Whitfield", lawyerId: "law-002", lawyerName: "Marcus Hale", courtName: "U.S. District Court, SDNY", courtRoom: "Courtroom 14", judge: "Hon. Robert Chen", date: "2026-04-05", time: "10:00", duration: "2 hours", status: "completed", outcome: "Motion to dismiss denied on all counts. Case proceeds to discovery.", createdAt: "2026-03-01T10:00:00Z", updatedAt: "2026-04-05T17:00:00Z" },
];
