import type { Lawyer } from "@/types/lawyer";

export const mockLawyers: Lawyer[] = [
  {
    id: "law-001",
    name: "Eleanor Voss",
    email: "eleanor.voss@lawcrest.com",
    phone: "+1 212-555-0101",
    designation: "Managing Partner",
    specializations: ["Corporate Law", "Contract Law"],
    barNumber: "NY-29384",
    experience: 22,
    bio: "Eleanor Voss leads LAWCREST with over two decades of experience in corporate governance, mergers and acquisitions, and complex commercial transactions. She has advised Fortune 500 companies and institutional investors across high-value cross-border deals. Known for her strategic acumen and meticulous attention to regulatory frameworks, Eleanor has consistently been recognized by leading legal directories as a top practitioner in corporate law.",
    education: ["J.D., Harvard Law School", "B.A. Economics, Yale University"],
    image: "/images/lawyers/eleanor-voss.jpg",
    status: "active",
    activeCases: 8,
    totalCases: 156,
    winRate: 94,
    caseIds: ["case-001", "case-005", "case-012"],
    joinedAt: "2004-03-15",
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2026-09-01T10:30:00Z",
  },
  {
    id: "law-002",
    name: "Marcus Hale",
    email: "marcus.hale@lawcrest.com",
    phone: "+1 212-555-0102",
    designation: "Senior Partner",
    specializations: ["Civil Litigation", "Employment Law"],
    barNumber: "NY-31290",
    experience: 18,
    bio: "Marcus Hale is a seasoned litigator with a track record of resolving complex commercial disputes and employment matters. He brings a measured, strategic approach to every case — combining thorough preparation with persuasive courtroom advocacy. His clients include multinational corporations, financial institutions, and senior executives navigating sensitive workplace matters.",
    education: ["J.D., Columbia Law School", "B.A. Political Science, Georgetown University"],
    image: "/images/lawyers/marcus-hale.jpg",
    status: "active",
    activeCases: 6,
    totalCases: 132,
    winRate: 91,
    caseIds: ["case-002", "case-007"],
    joinedAt: "2008-07-01",
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2026-08-28T14:15:00Z",
  },
  {
    id: "law-003",
    name: "Amara Sterling",
    email: "amara.sterling@lawcrest.com",
    phone: "+1 212-555-0103",
    designation: "Partner",
    specializations: ["Criminal Law", "Civil Litigation"],
    barNumber: "NY-34571",
    experience: 15,
    bio: "Amara Sterling is a former federal prosecutor who brings unparalleled courtroom instincts to LAWCREST's disputes practice. She has handled high-profile white-collar criminal matters, regulatory investigations, and complex civil disputes. Her ability to synthesize large volumes of evidence into compelling narratives has earned her recognition as one of the most formidable litigators in the jurisdiction.",
    education: ["J.D., Stanford Law School", "B.A. Criminology, University of Chicago"],
    image: "/images/lawyers/amara-sterling.jpg",
    status: "active",
    activeCases: 5,
    totalCases: 98,
    winRate: 89,
    caseIds: ["case-003", "case-009"],
    joinedAt: "2011-09-15",
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2026-09-05T09:00:00Z",
  },
  {
    id: "law-004",
    name: "Julian Mercer",
    email: "julian.mercer@lawcrest.com",
    phone: "+1 212-555-0104",
    designation: "Partner",
    specializations: ["Family Law", "Real Estate Law"],
    barNumber: "NY-37892",
    experience: 14,
    bio: "Julian Mercer heads the private client practice at LAWCREST, advising high-net-worth individuals and families on estate planning, matrimonial disputes, and property transactions. He is known for his empathetic yet pragmatic counsel, helping clients navigate emotionally charged situations with clarity and discretion. Julian has successfully resolved numerous high-value asset division matters.",
    education: ["J.D., NYU School of Law", "B.A. Psychology, Brown University"],
    image: "/images/lawyers/julian-mercer.jpg",
    status: "active",
    activeCases: 7,
    totalCases: 110,
    winRate: 92,
    caseIds: ["case-004", "case-008", "case-015"],
    joinedAt: "2012-04-01",
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2026-09-03T11:45:00Z",
  },
  {
    id: "law-005",
    name: "Sophia Castillo",
    email: "sophia.castillo@lawcrest.com",
    phone: "+1 212-555-0105",
    designation: "Senior Associate",
    specializations: ["Intellectual Property", "Corporate Law"],
    barNumber: "NY-42156",
    experience: 10,
    bio: "Sophia Castillo advises technology companies, creative enterprises, and institutional innovators on intellectual property protection, licensing, and enforcement. She has handled landmark patent disputes and complex trademark litigation with precision. Her ability to bridge the gap between technical complexity and legal strategy makes her an invaluable advisor to clients operating at the frontier of innovation.",
    education: ["J.D., Berkeley Law", "M.S. Computer Science, MIT"],
    image: "/images/lawyers/sophia-castillo.jpg",
    status: "active",
    activeCases: 4,
    totalCases: 64,
    winRate: 88,
    caseIds: ["case-006", "case-010"],
    joinedAt: "2016-08-15",
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2026-09-02T16:20:00Z",
  },
  {
    id: "law-006",
    name: "Richard Thorpe",
    email: "richard.thorpe@lawcrest.com",
    phone: "+1 212-555-0106",
    designation: "Partner",
    specializations: ["Tax & Compliance", "Corporate Law"],
    barNumber: "NY-28975",
    experience: 20,
    bio: "Richard Thorpe is one of the most experienced tax and compliance attorneys in the region. He advises corporations and private clients on complex tax structures, regulatory compliance, and government investigations. His deep understanding of both federal and state tax codes allows him to create innovative yet fully compliant solutions for sophisticated financial arrangements.",
    education: ["J.D., University of Pennsylvania Law School", "LL.M. Taxation, NYU School of Law"],
    image: "/images/lawyers/richard-thorpe.jpg",
    status: "active",
    activeCases: 5,
    totalCases: 143,
    winRate: 96,
    caseIds: ["case-011", "case-013"],
    joinedAt: "2006-01-10",
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2026-08-30T08:45:00Z",
  },
  {
    id: "law-007",
    name: "Diana Prescott",
    email: "diana.prescott@lawcrest.com",
    phone: "+1 212-555-0107",
    designation: "Senior Associate",
    specializations: ["Real Estate Law", "Contract Law"],
    barNumber: "NY-45231",
    experience: 8,
    bio: "Diana Prescott focuses on commercial real estate transactions, land use matters, and construction disputes. She has guided institutional investors and developers through complex acquisitions, lease negotiations, and zoning challenges. Her thorough due diligence process and proactive risk assessment approach ensure clients are protected throughout every phase of their real estate ventures.",
    education: ["J.D., Duke University School of Law", "B.S. Finance, University of Virginia"],
    image: "/images/lawyers/diana-prescott.jpg",
    status: "active",
    activeCases: 4,
    totalCases: 52,
    winRate: 90,
    caseIds: ["case-014", "case-016"],
    joinedAt: "2018-03-01",
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2026-09-04T13:30:00Z",
  },
  {
    id: "law-008",
    name: "Nathan Cross",
    email: "nathan.cross@lawcrest.com",
    phone: "+1 212-555-0108",
    designation: "Associate",
    specializations: ["Employment Law", "Legal Consultancy"],
    barNumber: "NY-48762",
    experience: 5,
    bio: "Nathan Cross represents employers and senior executives in workplace disputes, discrimination claims, and contract negotiations. He advises companies on employment policies, regulatory compliance, and workforce restructuring. His practical approach ensures that legal solutions are always aligned with his clients' broader business objectives.",
    education: ["J.D., Fordham University School of Law", "B.A. Labor Relations, Cornell University"],
    image: "/images/lawyers/nathan-cross.jpg",
    status: "active",
    activeCases: 3,
    totalCases: 28,
    winRate: 86,
    caseIds: ["case-017"],
    joinedAt: "2021-06-15",
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2026-09-06T10:00:00Z",
  },
  {
    id: "law-009",
    name: "Catherine Blackwell",
    email: "catherine.blackwell@lawcrest.com",
    phone: "+1 212-555-0109",
    designation: "Of Counsel",
    specializations: ["Corporate Law", "Legal Consultancy"],
    barNumber: "NY-22104",
    experience: 28,
    bio: "Catherine Blackwell brings nearly three decades of corporate counsel experience to LAWCREST. Having served as general counsel at two publicly traded companies, she offers a unique in-house perspective to the firm's corporate advisory practice. Catherine advises boards of directors on governance matters, executive compensation, and shareholder disputes.",
    education: ["J.D., University of Michigan Law School", "M.B.A., Wharton School"],
    image: "/images/lawyers/catherine-blackwell.jpg",
    status: "active",
    activeCases: 3,
    totalCases: 187,
    winRate: 93,
    caseIds: ["case-018", "case-019"],
    joinedAt: "2015-11-01",
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2026-08-25T15:00:00Z",
  },
  {
    id: "law-010",
    name: "Alexander Grant",
    email: "alexander.grant@lawcrest.com",
    phone: "+1 212-555-0110",
    designation: "Associate",
    specializations: ["Criminal Law", "Civil Litigation"],
    barNumber: "NY-51389",
    experience: 4,
    bio: "Alexander Grant is a rising talent in LAWCREST's disputes division. He assists senior partners in complex criminal defense matters and civil litigation while building his own client relationships. Known for his sharp analytical skills and his ability to prepare comprehensive legal briefs under tight deadlines, Alexander is quickly establishing himself as a trusted advocate.",
    education: ["J.D., University of Virginia School of Law", "B.A. Philosophy, Amherst College"],
    image: "/images/lawyers/alexander-grant.jpg",
    status: "active",
    activeCases: 3,
    totalCases: 19,
    winRate: 84,
    caseIds: ["case-020"],
    joinedAt: "2022-09-01",
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2026-09-07T09:30:00Z",
  },
];
