import type { Service } from "@/types/service";

export const mockServices: Service[] = [
  {
    id: "svc-001",
    title: "Corporate Law",
    slug: "corporate-law",
    shortDescription: "Strategic counsel for complex transactions, governance, and corporate growth.",
    fullDescription: "Our corporate law practice advises businesses at every stage of their lifecycle — from formation and governance to mergers, acquisitions, and strategic restructuring. We guide boards of directors and senior management through high-stakes decisions with a combination of commercial pragmatism and legal rigour. Our team has deep experience in cross-border transactions, regulatory compliance, and shareholder disputes.",
    icon: "Landmark",
    features: ["Mergers & Acquisitions", "Corporate Governance", "Joint Ventures", "Shareholder Agreements", "Due Diligence", "Regulatory Compliance"],
    image: "/images/services/corporate-law.jpg",
    order: 1,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "svc-002",
    title: "Civil Litigation",
    slug: "civil-litigation",
    shortDescription: "Decisive representation when the stakes are at their highest.",
    fullDescription: "Our litigation team represents individuals and organizations in complex civil disputes across state and federal courts. We bring a strategic, outcome-focused approach to every matter — combining thorough preparation with persuasive courtroom advocacy. From commercial disputes and breach of contract claims to class actions and appeals, we pursue the best possible result with tenacity and precision.",
    icon: "Gavel",
    features: ["Commercial Disputes", "Breach of Contract", "Class Actions", "Appeals", "Arbitration", "Mediation"],
    image: "/images/services/civil-litigation.jpg",
    order: 2,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "svc-003",
    title: "Criminal Law",
    slug: "criminal-law",
    shortDescription: "Vigorous defense for individuals and organizations facing criminal proceedings.",
    fullDescription: "Our criminal defense practice handles matters ranging from white-collar investigations and regulatory enforcement actions to serious individual criminal charges. Led by former federal prosecutors, our team understands the criminal justice system from both sides and uses that insight to build the strongest possible defense. We protect our clients' rights, reputations, and futures with unwavering commitment.",
    icon: "ShieldCheck",
    features: ["White-Collar Defense", "Regulatory Investigations", "Grand Jury Representation", "Federal Criminal Cases", "State Criminal Defense", "Internal Investigations"],
    image: "/images/services/criminal-law.jpg",
    order: 3,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "svc-004",
    title: "Family Law",
    slug: "family-law",
    shortDescription: "Discreet, considered advice protecting what matters most.",
    fullDescription: "Our family law practice handles sensitive personal matters with the empathy and discretion they deserve. We advise on divorce, child custody, prenuptial agreements, adoption, and domestic violence matters. We also work closely with our estate planning team to ensure that family wealth transitions are handled with care and foresight across generations.",
    icon: "Heart",
    features: ["Divorce & Separation", "Child Custody", "Prenuptial Agreements", "Adoption", "Estate Succession", "Domestic Relations"],
    image: "/images/services/family-law.jpg",
    order: 4,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "svc-005",
    title: "Real Estate Law",
    slug: "real-estate-law",
    shortDescription: "Comprehensive counsel for property transactions and development projects.",
    fullDescription: "Our real estate practice serves developers, investors, landlords, and tenants across the full spectrum of commercial and residential transactions. We handle acquisitions, dispositions, lease negotiations, zoning matters, and construction disputes with a practical understanding of the market forces that shape real estate decisions. Our team has guided transactions collectively valued at over $4 billion.",
    icon: "Building",
    features: ["Commercial Transactions", "Lease Negotiations", "Zoning & Land Use", "Construction Disputes", "Title Insurance", "Development Projects"],
    image: "/images/services/real-estate-law.jpg",
    order: 5,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "svc-006",
    title: "Employment Law",
    slug: "employment-law",
    shortDescription: "Protecting employer and employee rights in the modern workplace.",
    fullDescription: "Our employment law team advises both employers and senior executives on workplace matters including hiring and termination, employment agreements, non-compete provisions, discrimination claims, and workplace investigations. We help companies build compliant workplaces and help individuals protect their careers and professional reputations.",
    icon: "Users",
    features: ["Employment Agreements", "Workplace Discrimination", "Executive Compensation", "Non-Compete Disputes", "EEOC Proceedings", "Workplace Policies"],
    image: "/images/services/employment-law.jpg",
    order: 6,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "svc-007",
    title: "Tax & Compliance",
    slug: "tax-compliance",
    shortDescription: "Strategic tax planning and regulatory compliance advisory.",
    fullDescription: "Our tax practice helps individuals and businesses navigate the complex landscape of federal, state, and international tax obligations. We design tax-efficient structures, advise on compliance requirements, and represent clients in disputes with tax authorities. Our attorneys combine deep technical knowledge with commercial awareness to deliver practical solutions.",
    icon: "Calculator",
    features: ["Tax Planning & Strategy", "Regulatory Compliance", "IRS Disputes", "International Taxation", "Estate Tax Planning", "Corporate Tax Restructuring"],
    image: "/images/services/tax-compliance.jpg",
    order: 7,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "svc-008",
    title: "Intellectual Property",
    slug: "intellectual-property",
    shortDescription: "Protecting innovation, creativity, and competitive advantage.",
    fullDescription: "Our intellectual property practice helps innovators and creators protect their most valuable intangible assets. We handle patent prosecution and litigation, trademark registration and enforcement, copyright protection, and trade secret matters. Our team includes attorneys with advanced technical degrees who understand both the legal and technological dimensions of IP disputes.",
    icon: "Lightbulb",
    features: ["Patent Litigation", "Trademark Registration", "Copyright Protection", "Trade Secret Defense", "IP Licensing", "Technology Agreements"],
    image: "/images/services/intellectual-property.jpg",
    order: 8,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "svc-009",
    title: "Contract Law",
    slug: "contract-law",
    shortDescription: "Drafting, reviewing, and enforcing agreements that protect your interests.",
    fullDescription: "Our contract law practice handles the full lifecycle of commercial agreements — from initial drafting and negotiation through to enforcement and dispute resolution. We ensure that contracts are clear, enforceable, and aligned with our clients' strategic objectives. Our attorneys have reviewed thousands of contracts across virtually every industry and transaction type.",
    icon: "FileText",
    features: ["Contract Drafting", "Negotiation Support", "Breach of Contract", "Supply Agreements", "Service Agreements", "Distribution Contracts"],
    image: "/images/services/contract-law.jpg",
    order: 9,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "svc-010",
    title: "Legal Consultancy",
    slug: "legal-consultancy",
    shortDescription: "Trusted advisory for businesses navigating complex legal landscapes.",
    fullDescription: "Our legal consultancy practice provides ongoing advisory services to businesses that need regular access to sophisticated legal counsel without maintaining a large in-house team. We serve as an extension of our clients' leadership teams, providing strategic guidance on regulatory matters, risk management, compliance programs, and governance issues.",
    icon: "Scale",
    features: ["Risk Assessment", "Compliance Programs", "Governance Advisory", "Regulatory Strategy", "Legal Audits", "Policy Development"],
    image: "/images/services/legal-consultancy.jpg",
    order: 10,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2026-09-01T00:00:00Z",
  },
];
