import type { Task } from "@/types/task";

export const mockTasks: Task[] = [
  { id: "task-001", title: "Prepare discovery response — Harrington case", description: "Draft comprehensive response to Pacific Distribution's second set of interrogatories. Due before next hearing.", caseId: "case-001", caseName: "Harrington Enterprises — Corporate Contract Dispute", assignedTo: "law-001", assignedToName: "Eleanor Voss", status: "in-progress", priority: "high", dueDate: "2026-09-18", tags: ["discovery", "harrington"], createdAt: "2026-09-01T10:00:00Z", updatedAt: "2026-09-08T14:00:00Z" },
  { id: "task-002", title: "Review deposition transcripts — Whitfield", description: "Review and annotate deposition transcripts of former supervisor and HR director for hearing preparation.", caseId: "case-002", caseName: "Whitfield v. Anderson — Employment Discrimination Claim", assignedTo: "law-002", assignedToName: "Marcus Hale", status: "todo", priority: "high", dueDate: "2026-09-16", tags: ["deposition", "whitfield"], createdAt: "2026-09-05T09:00:00Z", updatedAt: "2026-09-05T09:00:00Z" },
  { id: "task-003", title: "Prepare CFO for OIG interview — Meridian", description: "Conduct mock interview session with Meridian CFO in preparation for OIG investigative interview on September 25.", caseId: "case-003", caseName: "Meridian Healthcare — Regulatory Investigation Defense", assignedTo: "law-003", assignedToName: "Amara Sterling", status: "in-progress", priority: "urgent", dueDate: "2026-09-23", tags: ["preparation", "meridian", "interview"], createdAt: "2026-09-02T11:00:00Z", updatedAt: "2026-09-07T16:00:00Z" },
  { id: "task-004", title: "Draft mediation brief — Ashworth Estate", description: "Prepare comprehensive mediation brief outlining client's position on trust distribution for second mediation session.", caseId: "case-004", caseName: "Ashworth Estate — Succession and Trust Dispute", assignedTo: "law-004", assignedToName: "Julian Mercer", status: "todo", priority: "high", dueDate: "2026-09-30", tags: ["mediation", "ashworth", "brief"], createdAt: "2026-09-03T10:00:00Z", updatedAt: "2026-09-03T10:00:00Z" },
  { id: "task-005", title: "File Markman hearing brief — Northstar", description: "Submit pre-hearing brief on claim construction issues for the upcoming Markman hearing.", caseId: "case-006", caseName: "Northstar Technologies — Patent Infringement Claim", assignedTo: "law-005", assignedToName: "Sophia Castillo", status: "review", priority: "urgent", dueDate: "2026-09-25", tags: ["markman", "northstar", "patent"], createdAt: "2026-09-01T08:00:00Z", updatedAt: "2026-09-08T11:00:00Z" },
  { id: "task-006", title: "Draft separation counter-proposal — Mitchell", description: "Prepare revised counter-proposal addressing employer's response to initial separation terms.", caseId: "case-007", caseName: "Mitchell — Executive Separation Negotiation", assignedTo: "law-002", assignedToName: "Marcus Hale", status: "todo", priority: "medium", dueDate: "2026-09-20", tags: ["separation", "mitchell"], createdAt: "2026-09-04T14:00:00Z", updatedAt: "2026-09-04T14:00:00Z" },
  { id: "task-007", title: "Title search update — Chen property dispute", description: "Commission updated title search for 550 Broadway property to verify ownership chain and encumbrances.", caseId: "case-008", caseName: "Chen Family — Property Ownership Dispute", assignedTo: "law-004", assignedToName: "Julian Mercer", status: "completed", priority: "medium", dueDate: "2026-09-05", completedAt: "2026-09-04T15:00:00Z", tags: ["title-search", "chen"], createdAt: "2026-08-25T10:00:00Z", updatedAt: "2026-09-04T15:00:00Z" },
  { id: "task-008", title: "Prepare TRO extension motion — Northstar trade secret", description: "Draft and file motion to extend temporary restraining order. Compile supporting declarations.", caseId: "case-010", caseName: "Northstar Technologies — Trade Secret Misappropriation", assignedTo: "law-005", assignedToName: "Sophia Castillo", status: "completed", priority: "urgent", dueDate: "2026-09-12", completedAt: "2026-09-11T18:00:00Z", tags: ["TRO", "northstar", "trade-secret"], createdAt: "2026-09-01T08:00:00Z", updatedAt: "2026-09-11T18:00:00Z" },
  { id: "task-009", title: "SEC filing review — Pinnacle", description: "Review and finalize amended registration statement and beneficial ownership filings.", caseId: "case-013", caseName: "Pinnacle Financial — SEC Reporting Compliance", assignedTo: "law-006", assignedToName: "Richard Thorpe", status: "in-progress", priority: "high", dueDate: "2026-09-22", tags: ["SEC", "pinnacle", "compliance"], createdAt: "2026-09-02T10:00:00Z", updatedAt: "2026-09-07T14:00:00Z" },
  { id: "task-010", title: "Lease holdover damage calculation — Dominion", description: "Prepare detailed calculation of holdover damages including lost rent and property modification costs.", caseId: "case-014", caseName: "Dominion Real Estate — Commercial Lease Dispute", assignedTo: "law-007", assignedToName: "Diana Prescott", status: "review", priority: "medium", dueDate: "2026-09-24", tags: ["damages", "dominion", "lease"], createdAt: "2026-09-03T09:00:00Z", updatedAt: "2026-09-08T10:30:00Z" },
  { id: "task-011", title: "Non-compete analysis — Kessler", description: "Research enforceability of non-compete provisions under current New York law and prepare memorandum.", caseId: "case-017", caseName: "Kessler v. Apex Capital — Non-Compete Enforcement", assignedTo: "law-008", assignedToName: "Nathan Cross", status: "completed", priority: "high", dueDate: "2026-09-10", completedAt: "2026-09-09T16:00:00Z", tags: ["non-compete", "kessler", "research"], createdAt: "2026-08-28T10:00:00Z", updatedAt: "2026-09-09T16:00:00Z" },
  { id: "task-012", title: "FAR compliance checklist — Atlas contract", description: "Complete Federal Acquisition Regulation compliance checklist for $45M infrastructure contract.", caseId: "case-018", caseName: "Atlas Infrastructure — Government Contract Review", assignedTo: "law-009", assignedToName: "Catherine Blackwell", status: "in-progress", priority: "medium", dueDate: "2026-09-19", tags: ["FAR", "atlas", "compliance"], createdAt: "2026-09-01T11:00:00Z", updatedAt: "2026-09-06T15:00:00Z" },
  { id: "task-013", title: "Client engagement letter — Cascade Ventures", description: "Draft standard engagement letter for prospective client Cascade Ventures LLC.", assignedTo: "law-001", assignedToName: "Eleanor Voss", status: "todo", priority: "low", dueDate: "2026-09-25", tags: ["engagement", "cascade"], createdAt: "2026-09-08T09:00:00Z", updatedAt: "2026-09-08T09:00:00Z" },
  { id: "task-014", title: "Monthly billing review — All active matters", description: "Review and approve billing entries for all active matters before end-of-month invoicing cycle.", assignedTo: "law-001", assignedToName: "Eleanor Voss", status: "todo", priority: "medium", dueDate: "2026-09-28", tags: ["billing", "admin"], createdAt: "2026-09-01T08:00:00Z", updatedAt: "2026-09-01T08:00:00Z" },
  { id: "task-015", title: "HIPAA compliance framework draft — Meridian", description: "Draft initial HIPAA compliance framework addressing identified data security vulnerabilities.", caseId: "case-009", caseName: "Meridian Healthcare — HIPAA Compliance Remediation", assignedTo: "law-003", assignedToName: "Amara Sterling", status: "todo", priority: "medium", dueDate: "2026-10-01", tags: ["HIPAA", "meridian", "compliance"], createdAt: "2026-09-05T10:00:00Z", updatedAt: "2026-09-05T10:00:00Z" },
  { id: "task-016", title: "Zoning variance research — Dominion project", description: "Research precedent for similar zoning variance applications in Lower Manhattan and community board decisions.", caseId: "case-016", caseName: "Dominion Real Estate — Zoning Variance Application", assignedTo: "law-007", assignedToName: "Diana Prescott", status: "in-progress", priority: "medium", dueDate: "2026-09-20", tags: ["zoning", "dominion", "research"], createdAt: "2026-08-15T09:00:00Z", updatedAt: "2026-09-04T13:00:00Z" },
  { id: "task-017", title: "Expert witness coordination — Meridian investigation", description: "Coordinate with forensic accounting expert for preparation of supplemental report.", caseId: "case-003", caseName: "Meridian Healthcare — Regulatory Investigation Defense", assignedTo: "law-003", assignedToName: "Amara Sterling", status: "review", priority: "high", dueDate: "2026-09-19", tags: ["expert", "meridian"], createdAt: "2026-09-02T14:00:00Z", updatedAt: "2026-09-08T09:00:00Z" },
  { id: "task-018", title: "Due diligence update — Harrington merger", description: "Update due diligence report with newly disclosed financial information from target company.", caseId: "case-005", caseName: "Harrington Enterprises — Merger Compliance Review", assignedTo: "law-001", assignedToName: "Eleanor Voss", status: "todo", priority: "medium", dueDate: "2026-09-22", tags: ["due-diligence", "harrington", "merger"], createdAt: "2026-09-06T10:00:00Z", updatedAt: "2026-09-06T10:00:00Z" },
  { id: "task-019", title: "International tax treaty analysis — Drake", description: "Analyze US-UK tax treaty provisions applicable to dual-citizen investment income and property gains.", caseId: "case-020", caseName: "Drake — International Tax Advisory", assignedTo: "law-010", assignedToName: "Alexander Grant", status: "in-progress", priority: "medium", dueDate: "2026-09-26", tags: ["tax", "drake", "international"], createdAt: "2026-09-01T10:00:00Z", updatedAt: "2026-09-07T11:00:00Z" },
  { id: "task-020", title: "Settlement demand letter — Harrington case", description: "Draft settlement demand letter for consideration before proceeding to trial preparation phase.", caseId: "case-001", caseName: "Harrington Enterprises — Corporate Contract Dispute", assignedTo: "law-001", assignedToName: "Eleanor Voss", status: "completed", priority: "high", dueDate: "2026-08-30", completedAt: "2026-08-29T17:00:00Z", tags: ["settlement", "harrington"], createdAt: "2026-08-15T10:00:00Z", updatedAt: "2026-08-29T17:00:00Z" },
];
