import type { Testimonial } from "@/types/testimonial";

export const mockTestimonials: Testimonial[] = [
  {
    id: "test-001",
    quote: "LAWCREST brought clarity to a situation that felt impossible. Their strategic guidance during our merger saved us millions and gave our board the confidence to move forward decisively.",
    clientName: "Richard Harrington",
    clientDesignation: "Chairman",
    clientCompany: "Harrington Enterprises",
    clientImage: "/images/testimonials/richard-harrington.jpg",
    rating: 5,
    featured: true,
    createdAt: "2026-06-15T10:00:00Z",
  },
  {
    id: "test-002",
    quote: "They see around corners. More importantly, they help us see around them too. Their counsel has been instrumental in navigating regulatory challenges across three jurisdictions.",
    clientName: "Margaret Chen",
    clientDesignation: "Co-Founder",
    clientCompany: "Chen Holdings",
    clientImage: "/images/testimonials/margaret-chen.jpg",
    rating: 5,
    featured: true,
    createdAt: "2026-05-20T14:00:00Z",
  },
  {
    id: "test-003",
    quote: "In a matter that demanded both legal precision and human empathy, Julian Mercer and his team delivered beyond our expectations. They protected what mattered most to our family.",
    clientName: "Victoria Ashworth",
    clientDesignation: "Beneficiary",
    clientCompany: "Ashworth Family Trust",
    clientImage: "/images/testimonials/victoria-ashworth.jpg",
    rating: 5,
    featured: true,
    createdAt: "2026-07-01T09:00:00Z",
  },
  {
    id: "test-004",
    quote: "Their judgment is measured, direct, and always focused on what matters next. LAWCREST does not just solve legal problems — they help us make better business decisions.",
    clientName: "Daniel Foster",
    clientDesignation: "CEO",
    clientCompany: "Northstar Technologies",
    clientImage: "/images/testimonials/daniel-foster.jpg",
    rating: 5,
    featured: false,
    createdAt: "2026-04-10T11:00:00Z",
  },
  {
    id: "test-005",
    quote: "When our company faced a regulatory investigation, Amara Sterling assembled a defense that was thorough, aggressive where it needed to be, and ultimately successful. We cannot recommend her highly enough.",
    clientName: "Dr. Patricia Simmons",
    clientDesignation: "Chief Medical Officer",
    clientCompany: "Meridian Healthcare Group",
    clientImage: "/images/testimonials/patricia-simmons.jpg",
    rating: 5,
    featured: false,
    createdAt: "2026-08-05T15:00:00Z",
  },
  {
    id: "test-006",
    quote: "The tax restructuring that Richard Thorpe designed for our firm saved us over $2.3 million annually while keeping us fully compliant. That is the kind of work that justifies every dollar in legal fees.",
    clientName: "Lawrence Goldstein",
    clientDesignation: "Managing Director",
    clientCompany: "Pinnacle Financial Services",
    clientImage: "/images/testimonials/lawrence-goldstein.jpg",
    rating: 5,
    featured: false,
    createdAt: "2026-03-18T10:30:00Z",
  },
];
